index:
    path: /
    controller: App\Controller\AppController::index

planos:
    path: /planos
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:   'app/planos.html.twig'
        statusCode: 200
        # cache
        maxAge:    86400
        sharedAge: 86400
        # whether or not caching should apply for client caches only
        private: true
        # optionally you can define some arguments passed to the template
        #context:
        #    site_name: 'ACME'
        #    theme: 'dark'